// StayFrank Database Types
// This will be auto-generated by Supabase, but here's the expected structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string | null
          full_name: string | null
          cell_phone: string | null
          company_name: string | null
          company_url: string | null
          role: 'manager' | 'officer'
          status: 'pending' | 'active' | 'denied'
          parent_id: string | null
          invite_token: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email?: string | null
          full_name?: string | null
          cell_phone?: string | null
          company_name?: string | null
          company_url?: string | null
          role?: 'manager' | 'officer'
          status?: 'pending' | 'active' | 'denied'
          parent_id?: string | null
          invite_token?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string | null
          full_name?: string | null
          cell_phone?: string | null
          company_name?: string | null
          company_url?: string | null
          role?: 'manager' | 'officer'
          status?: 'pending' | 'active' | 'denied'
          parent_id?: string | null
          invite_token?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      funding_reasons: {
        Row: {
          id: string
          value: string
          label: string
          display_order: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          value: string
          label: string
          display_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          value?: string
          label?: string
          display_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      submissions: {
        Row: {
          id: string
          user_id: string
          property_address: string
          home_value: number | null
          mortgage_balance: number | null
          owner_names: string[] | null
          property_type: string | null
          state: string | null
          // Personal Details
          owner_emails: string[] | null
          owner_phones: string[] | null
          owner_credit_scores: string[] | null
          mortgage_current: boolean | null
          money_reason: string | null
          money_reasons: string[] | null
          helpful_context: string | null
          money_amount: string | null
          // Eligibility
          sl_eligible: boolean
          sl_offer_amount: number | null
          sl_ineligibility_reasons: string[] | null
          hei_eligible: boolean
          hei_max_investment: number | null
          hei_ineligibility_reasons: string[] | null
          equityadvance_deal_id: string | null
          everflow_tracking_link: string | null
          submitted_to_crm: boolean
          submitted_to_crm_at: string | null
          hubspot_contact_id: string | null
          hubspot_deal_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          property_address: string
          home_value?: number | null
          mortgage_balance?: number | null
          owner_names?: string[] | null
          property_type?: string | null
          state?: string | null
          // Personal Details
          owner_emails?: string[] | null
          owner_phones?: string[] | null
          owner_credit_scores?: string[] | null
          mortgage_current?: boolean | null
          money_reason?: string | null
          money_reasons?: string[] | null
          helpful_context?: string | null
          money_amount?: string | null
          // Eligibility
          sl_eligible?: boolean
          sl_offer_amount?: number | null
          sl_ineligibility_reasons?: string[] | null
          hei_eligible?: boolean
          hei_max_investment?: number | null
          hei_ineligibility_reasons?: string[] | null
          equityadvance_deal_id?: string | null
          everflow_tracking_link?: string | null
          submitted_to_crm?: boolean
          submitted_to_crm_at?: string | null
          hubspot_contact_id?: string | null
          hubspot_deal_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          property_address?: string
          home_value?: number | null
          mortgage_balance?: number | null
          owner_names?: string[] | null
          property_type?: string | null
          state?: string | null
          // Personal Details
          owner_emails?: string[] | null
          owner_phones?: string[] | null
          owner_credit_scores?: string[] | null
          mortgage_current?: boolean | null
          money_reason?: string | null
          money_reasons?: string[] | null
          helpful_context?: string | null
          money_amount?: string | null
          // Eligibility
          sl_eligible?: boolean
          sl_offer_amount?: number | null
          sl_ineligibility_reasons?: string[] | null
          hei_eligible?: boolean
          hei_max_investment?: number | null
          hei_ineligibility_reasons?: string[] | null
          equityadvance_deal_id?: string | null
          everflow_tracking_link?: string | null
          submitted_to_crm?: boolean
          submitted_to_crm_at?: string | null
          hubspot_contact_id?: string | null
          hubspot_deal_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      user_roles: {
        Row: {
          id: string
          user_id: string
          role: 'admin'
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          role: 'admin'
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          role?: 'admin'
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      has_role: {
        Args: {
          user_id: string
          required_role: 'admin'
        }
        Returns: boolean
      }
    }
    Enums: {
      app_role: 'admin'
      user_role: 'manager' | 'officer'
      user_status: 'pending' | 'active' | 'denied'
    }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T]
